openapi: 3.0.0
info:
  title: Lelang Online
  version: 1.0.0
servers:
- url: http://localhost:8000
tags:
- name: Authentication
  description: Authentication
- name: Product
  description: Product
- name: Order
  description: Order
paths:
                
  /api/v1/buyer/product/all:
    get: 
      description: Get all data product
      summary: Get all data product
      tags:
      - Product
      responses: 
        200:
          description: Show all data product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/example_respon_200_list_product'
        204:
          description: No content
                
  /api/v1/buyer/product/{id}:
    get:
      description: Get all data product by id
      summary: Get all data product by id
      tags:
      - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses: 
        200:
          description: Show all data product by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/example_respon_200_list_product'
        
        404:
          description: Data doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/example_respon_404'
                 
  /api/v1/buyer/order/buy:
    post:
      description: Order product 
      summary: Order product
      tags:
      - Order
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bid_price:
                  type: integer
                  example: 200000
      responses:
        201:
          description: Order Success 
          content: 
            aplication/json:
              schema:
                $ref: "#/components/schemas/example_respon_201_order_buy"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example_respon_400"    
        
  /api/v1/buyer/order/price-appeal/{id}:
    put:
      description: Update price
      summary: Update price
      tags: 
      - Order
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema: 
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bid_price:
                  type: integer
                  example: 230000
      responses:
        201:
          description: Update price success
          content:
            aplication/json:
              schema:
                $ref: "#/components/schemas/example_respon_201_order_price_appeal"
        400:
          description: Bad request
          content:
            aplication/json:
              schema: 
                $ref: "#/components/schemas/example_respon_400"
                    
  /api/v1/buyer/order:
    get: 
      description: Get all data order
      summary: Get all data order
      tags:
      - Order
      security:
      - bearerAuth: []
      responses: 
        200:
          description: Show all data order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example_respon_200_list_order" 
        204:
          description: No content
                
  /api/v1/buyer/order/product/{id}:
    get: 
      description: Get data order by id
      summary: Get data order by id
      tags:
      - Order
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses: 
        200:
          description: Show data order by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example_respon_200_list_order"
        404:
          description: Data doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/example_respon_404'
    
components:
  schemas:
    
    example_respon_200_list_product:
      type: object
      properties: 
        status:
          type: string
          example: Success
        data:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: Jam Tangan Casio
            description:
              type: string
              example:  Jam tangan ini didesain sederhana dengan materi resin yang ringan. Tampilan feminin yang simpel dapat digunakan sehari-hari. 
            base_price:
              type: integer
              example: 250000
            user:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                image_url:
                  type: string
                  example: profil.jpg
                address:
                  type: string
                  example: Jakarta
            status:
              type: string
              example: available
            category:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name: 
                  type: string
                  example: aksesoris
            deletedAt:
              type: string
              example: null
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
              
    example_respon_201_order_buy:
      type: object
      properties:
        status:
          type: string
          example: Order success
        data:
          type: object
          properties:
            id:
              type: integer
              example: 1
            product:
              type: object
              properties:
                id:
                  type: integer 
                  example: 1
                name:
                  type: string
                  example: Jam Casio
                base_price: 
                  type: integer
                  example: 250000
            buyer_id:
              type: integer
              example: 1
            bid_price:
              type: integer
              example: 200000
            status:
              type: string
              example: menunggu
            seller_id:
              type: integer
              example: 1
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
    
    example_respon_201_order_price_appeal:
      type: object
      properties:
        status:
          type: string
          example: Update bid success
        data:
          type: object
          properties:
            id:
              type: integer
              example: 1
            product:
              type: object
              properties:
                id:
                  type: integer 
                  example: 1
                name:
                  type: string
                  example: Jam Casio
                base_price: 
                  type: integer
                  example: 250000
            buyer_id:
              type: integer
              example: 1
            bid_price:
              type: integer
              example: 230000
            status:
              type: string
              example: menunggu
            seller_id:
              type: integer
              example: 1
            updatedAt:
              type: string
              format: date-time
    
    example_respon_200_list_order:
      type: object
      properties: 
        status:
          type: string
          example: Success
        data:
          type: object
          properties:
            id:
              type: integer
              example: 1
            product:
              type: object
              properties:
                id:
                  type: integer 
                  example: 1
                name:
                  type: string
                  example: Jam Casio
                base_price: 
                  type: integer
                  example: 250000
                user_id:
                  type: integer
                  example: 1
            buyer_id:
              type: integer
              example: 1
            bid_price:
              type: integer
              example: 200000
            status:
              type: string
              example: menunggu
            seller_id:
              type: integer
              example: 1
            deletedAt:
              type: string
              example: null
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
              
    example_respon_400:
      type: object
      properties: 
        status:
          type: string
          example: Error
        message:
          type: string
          example: Bad Request
    
    example_respon_404:
      type: object
      properties: 
        status:
          type: string
          example: Error
        message:
          type: string
          example: Data not found
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
